---
title: "singleR_annotation"
author: "Charles"
date: '2022-07-29'
output: html_document
editor_options: 
  chunk_output_type: console
---

## Description

I want to automatically annotate the cells of the seurat object from GSE178318, using [SingleR](https://bioconductor.org/packages/release/bioc/vignettes/SingleR/inst/doc/SingleR.html).

## Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Load the libraries

```{r libraries}
library(Seurat)
library(SingleR)
library(celldex)
library(randomcoloR)
library(ggplot2)
library(cowplot)
library(grid)
library(gridExtra) 
library(ggpubr)
library(openxlsx)
library(tidyverse)
```

## load the data set and run SingleR

```{r data_loaded}
# create path
path_to_obj <- "/mnt/DATA/Charles/External collaborations/DFKZ/GSE178318/QC_clustering_DEA/objects/integrated_and_clustered.rds"

# read in the data
seurat <- readRDS(path_to_obj)
seurat

# get sct normalised counts
sct_seurat <- GetAssayData(seurat,
                           assay = "SCT",
                           slot = "data")

DimPlot(seurat)

hpca.se <-celldex::HumanPrimaryCellAtlasData()
hpca.se

# perform the annotation
pred.hesc <- SingleR(test = sct_seurat, ref = hpca.se, assay.type.test=1,
    labels = hpca.se$label.main)

# fit the predictions
all(rownames(pred.hesc) == colnames(sct_seurat)) #T


# fit predictions
seurat$singleR_humanAtlasMain_1 <- pred.hesc$pruned.labels

# get distinct colours
set.seed(123)
colours <- distinctColorPalette(200)

# visualise without legend
DimPlot(seurat, group.by = "singleR_humanAtlasMain_1",
        cols = colours) + NoLegend()
ggsave(filename=paste0("figures", "/", "no_legend_umap_cell_types",
                       ".pdf"), width = 5, 
       height = 5, units = 'in', dpi = 300)

# get_legend
the_ggplot <- DimPlot(seurat, group.by = "singleR_humanAtlasMain_1",
                                    cols = colours) 
the_legend <- get_legend(the_ggplot)

as_ggplot(the_legend)
ggsave(filename=paste0("figures", "/", "legend_umap_cell_types",
                       ".pdf"), width = 5, 
       height = 5, units = 'in', dpi = 300)
```

## Perform differential expressed genes analysis

```{r DEA}
# create path
path_to_obj <- "/mnt/DATA/Charles/External collaborations/DFKZ/GSE178318/QC_clustering_DEA/objects/integrated_and_clustered.rds"

# read in the data
seurat <- readRDS(path_to_obj)
seurat

# set appropriate ident
Idents(seurat) <- seurat$singleR_humanAtlasMain_1

markers <- FindAllMarkers(seurat,
                          only.pos = T,
                          assay = "RNA",
                          slot = "data")

write.xlsx(markers,
           "results/cell_markers.xlsx",
           row.names = TRUE)

# read in the markers dataset
markers <- read.xlsx("results/cell_markers.xlsx",
                        rowNames  = TRUE)
head(markers, 15)

# get top markers
top_markers <- markers %>% 
                    group_by(cluster) %>%
                    top_n(5, avg_log2FC)

# visualise the expression of certain markers
FeaturePlot(seurat, features = "EPCAM", order = T, raster = FALSE) +
   theme(aspect.ratio = 1)

FeaturePlot(seurat, features = c("KRT8"), 
            order = T, raster = FALSE) +
  theme(aspect.ratio = 1)


FeaturePlot(seurat, features = c("KRT18"), 
            order = T, raster = FALSE) +
  theme(aspect.ratio = 1)

# all cell types are hard to visualise in a single heatmap
# For now cells of interest are the epithelial cells which I can clearly identify
# I will progressively review the identities of the other cell types, as proposed by the singleR algorithm

# identifying cluster of epithelial cells
DimPlot(seurat, group.by = "integrated_snn_res.0.05", label = T)

# assess number of cells in the epithelial cluster
table(seurat$integrated_snn_res.0.05) 

# cluster 9 at integrated_snn_res.0.05 consists of the epithelial cells 
# cluster 9 has 7905 cells.
```

## Identify patients treated with PC or not

```{r treatment_status}
# create path
path_to_obj <- "/mnt/DATA/Charles/External collaborations/DFKZ/GSE178318/QC_clustering_DEA/objects/integrated_and_clustered.rds"

# read in the data
seurat <- readRDS(path_to_obj)
seurat

table(seurat$subjectID)

# assign treatment groups
seurat$treatment_status <- seurat$subjectID

seurat$treatment_status[seurat$treatment_status%in%c("COL15", "COL17", "COL18")] <- "PC"
seurat$treatment_status[!seurat$treatment_status%in%"PC"] <- "no_PC"

table(seurat$treatment_status)

# set raster to false
DimPlot(seurat,
        group.by = "treatment_status", 
        split.by = "group",
        raster = FALSE)

# umap of treatment status
DimPlot(seurat,
        group.by = "treatment_status", 
        raster = FALSE) + 
  theme(aspect.ratio = 1)

# umap of groups
DimPlot(seurat,
        group.by = "group", 
        raster = FALSE) + 
  theme(aspect.ratio = 1)

# umap of groups
DimPlot(seurat,
        group.by = "group", 
        split.by = "group",
        raster = FALSE) + 
  theme(aspect.ratio = 1)

saveRDS(seurat, 
        path_to_obj)
```