---
title: "Endothelial_script"
author: "Charles"
date: "2 8 2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Description

To subcluster the endothelial cluster and perform necessary visualisations.

## Set up

```{r setup, include=FALSE}
.libPaths("V:/GROUPS/AG Ramming/Fellows/Charles/R-4.1.1/library")
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Load libraries

```{r load_libraries}
library(Seurat)
library(SeuratObject)
library(SeuratWrappers)
library(SeuratDisk)
library(ggplot2)
library(dplyr)
library(tidyr)
library(openxlsx)
library(enrichR)
```

## Load the dataset

```{r data_loading}
path <- "V:/GROUPS/AG Ramming/Fellows/Charles/Analyses/External collaborations/DFKZ/GSE178318/GSE178318/cell_annotation/singleR/objects/epithelial_cluster.rds"

epith <- readRDS(path)
DimPlot(epith)
```

## Subcluster the epithelial cells

```{r subclustering}
DefaultAssay(epith) <- "integrated"
epith <- RunPCA(epith, npcs = 50) 
epith <- RunUMAP(epith, reduction = "pca", dims = 1:30)
epith <- FindNeighbors(epith, reduction = "umap", dims = 1:2)
epith <- FindClusters(epith, resolution = seq(0.05, 2, 0.05))
DimPlot(epith)

DefaultAssay(epith) <- "RNA"
epith <- NormalizeData(epith)
DimPlot(epith)
```

## Visualisations

```{r visualistation}
DimPlot(epith, group.by = "group") + 
  theme(aspect.ratio = 1)
ggsave("figures/umap_epith_per_group.pdf")


DimPlot(epith, label = TRUE,
        group.by = "integrated_snn_res.0.05") + 
  theme(aspect.ratio = 1)
ggsave("figures/umap_epith_low_res_clust.pdf")

DimPlot(epith, label = TRUE,split.by = "group",
        group.by = "integrated_snn_res.0.05") + 
  theme(aspect.ratio = 1) + NoLegend()
ggsave("figures/umap_epith_low_res_clust_split.pdf",
       height = 6, width = 6, dpi = 400)

lymphotoxins <- c("LTBR","TNFRSF1A","LTA", "LTB", "TNFSF14")

VlnPlot(epith,
        lymphotoxins[1:2],split.by = "treatment_status",
        group.by = "group", pt.size = .01)
ggsave("figures/Vlnplot_lymphotoxins_per_group_1.pdf")

VlnPlot(epith,
        lymphotoxins[3:5],
        group.by = "group", pt.size = .01)
ggsave("figures/Vlnplot_lymphotoxins_per_group_2.pdf")

for(l in lymphotoxins){
  VlnPlot(epith,
          l, split.by = "treatment_status",
          group.by = "group", pt.size = .01)
ggsave(paste0("figures/Vlnplot_",l, "_pc_vs_nopc.pdf"))
  
}
```

## Marker genes of various tissue of origin

```{r tissue_markers}
# Epithelial cells are meaningless in PBMCs
# so I remove those that are present in PBMCs

Idents(epith) <- epith$group

epith_no_pbmc <- subset(epith,
                        idents = "PBMC",
                        invert = TRUE)

epith_no_pbmc_markers <- FindAllMarkers(epith_no_pbmc,
                                        assay = "RNA",
                                        slot = "data",
                                        only.pos = TRUE,
                                        logfc.threshold = 0,
                                        min.pct = 0)

# write out the epith_no_pbmc_markers results
write.xlsx(epith_no_pbmc_markers,
           "results/epith_no_pbmc_markers.xlsx",
           rownames = TRUE)

# enrichment analysis
# for CRC
sig_epith_no_pbmc_markers <- subset(epith_no_pbmc_markers,
                                    p_val_adj < 0.05)

CRC <- subset(sig_epith_no_pbmc_markers,
              cluster == "CRC")

# get database
dbs <- listEnrichrDbs()
tail(dbs, 100)
dbs_keep <- "MSigDB_HalCRCark_2020"
CRC_pways <- enrichr(CRC$gene,
                     dbs_keep)
plotEnrich(CRC_pways[[1]])

write.xlsx(CRC_pways,
           "results/CRC_msigdb2020.xlsx",
           rowNames = TRUE)


# for LM
sig_epith_no_pbmc_markers <- subset(epith_no_pbmc_markers,
                                    p_val_adj < 0.05)

LM <- subset(sig_epith_no_pbmc_markers,
              cluster == "LM")

# get database
dbs <- listEnrichrDbs()
tail(dbs, 100)
dbs_keep <- "MSigDB_Hallmark_2020"
LM_pways <- enrichr(LM$gene,
                     dbs_keep)
plotEnrich(LM_pways[[1]])

write.xlsx(LM_pways,
           "results/LM_msigdb2020.xlsx",
           rowNames = TRUE)

top_markers <- epith_no_pbmc_markers %>%
                    group_by(cluster) %>%
                    top_n(10, avg_log2FC)

epith_no_pbmc <- ScaleData(epith_no_pbmc, 
                           features = rownames(epith_no_pbmc))

DoHeatmap(epith_no_pbmc, features = top_markers$gene)
ggsave("figures/heatmap_epith_tissue_markers.pdf",
       height = 6, width = 6, dpi = 400)

# obtain degs between PC and no_PC conditions for 
# each tissue
clusters_oi <- unique(epith_no_pbmc$group)
conditions <- "treatment_status"
conditions_oi <- c("no_PC", "PC")
ident_oi <- "group"

multi_DEG_analysis <- function(seurat, ident_oi,
                               conditions,
                               clusters_oi,
                               conditions_oi){
  
                        Idents(seurat) <- ident_oi
                              
                        for (cluster in clusters_oi) {
                                
                            sub_clust <- subset(seurat,
                                                    idents = cluster)
                                
                            Idents(sub_clust) <- conditions
                                
                            degs <- FindMarkers(sub_clust,
                                                assay = "RNA",
                                                slot = "data",
                                                ident.1 = 
                                                conditions_oi[1],
                                                min.pct = 0,
                                                logfc.threshold = 0)
                                write.xlsx(degs,
                                           paste0("results/",cluster,
                                                  "_degs_",
                                                  conditions_oi[1],
                                                  "_vs_",
                                                  conditions_oi[2],
                                                  ".xlsx"),
                                           rowNames = TRUE)
                                
                              }
                              
} 

multi_DEG_analysis(seurat = epith_no_pbmc, 
                   ident_oi = ident_oi,
                   conditions_oi = conditions_oi,
                   conditions = conditions,
                   clusters_oi = clusters_oi)
```

## Find markers per cluster

```{r cluster_markers}
Idents(epith) <- epith$integrated_snn_res.0.05

epith_cluster_markers <- FindAllMarkers(epith,
                                        assay = "RNA",
                                        slot = "data",
                                        only.pos = T)

write.xlsx(epith_cluster_markers,
           "results/epith_cluster_markers.xlsx",
           rowNames = TRUE)

the_top <- epith_cluster_markers %>%
                    group_by(cluster) %>%
                    top_n(10, avg_log2FC)

epith <- ScaleData(epith, features = rownames(epith))

DoHeatmap(epith,
          features = the_top$gene)
```
